---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  CART_HOST: "cart:80"
  USER_HOST: "user"
  AMQP_HOST: "rabbitmq"
---
apiVersion: v1
kind: Pod
metadata:
 name: payment
 labels:
  name: payment
  tier: app
spec:
 containers:
 - name: user
   imagePullPolicy: Always
   image: mshiva7396/payment:k8
   ports:
   - containerPort: 8080
   envFrom:
    - configMapRef:
        name: payment-config
   resources:
     requests:
       cpu: "100m"
       memory: "128Mi"
     limits:
       cpu: "150m"
       memory: "200Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    name: payment
    tier: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080