---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
data:
  CATALOGUE_HOST: "http://catalogue"
  REDIS_HOST: "redis"
---
apiVersion: v1
kind: Pod
metadata:
 name: cart
 labels:
  name: cart
  tier: app
spec:
 containers:
 - name: cart
   imagePullPolicy: Always
   image: mshiva7396/cart:k8
   ports:
   - containerPort: 8080
   envFrom:
    - configMapRef:
        name: cart-config
   resources:
     requests:
       cpu: "100m"
       memory: "128Mi"
     limits:
       cpu: "150m"
       memory: "200Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    name: cart
    tier: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080