---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
data:
  CART_EBDPOINT: "cart"
  DB_HOST: "mysql"
---
apiVersion: v1
kind: Pod
metadata:
 name: shipping
 labels:
  name: shipping
  tier: app
spec:
 containers:
 - name: user
   imagePullPolicy: Always
   image: mshiva7396/shipping:k8
   ports:
   - containerPort: 8080
   envFrom:
    - configMapRef:
        name: shipping-config
   resources:
     requests:
       cpu: "100m"
       memory: "128Mi"
     limits:
       cpu: "150m"
       memory: "200Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    name: shipping
    tier: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080