---
apiVersion: v1
kind: Pod
metadata:
 name: mongodb
 labels:
  name: mongodb
  tier: db
spec:
 containers:
  - name: mongodb
    image: mshiva7396/mongodb:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    name: mongodb
    tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017