---
apiVersion: v1
kind: Pod
metadata:
 name: catalogue
 labels:
  name: catalogue
  tier: app
spec:
 containers:
 - name: catalogue
   imagePullPolicy: Always
   image: mshiva7396/catalogue:v1
   ports:
   - containerPort: 8080
   resources:
     requests:
       cpu: "100m"
       memory: "128Mi"
     limits:
       cpu: "150m"
       memory: "200Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  type: LoadBalancer
  selector:
    name: catalogue
    tier: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080